name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: helaili/jekyll-action@2.5.0
        with:
          pre_build_commands: git config --global http.version HTTP/1.1; apk fetch git-lfs;
          token: ${{ secrets.JEKYLL_PAT }}
          target_branch: 'gh-pages'